### ISSUE TITLE
Tweaking a data set to achieve target r

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-correlation#6]
0.0.7

In ESCI 'See r' with 'Generate data set with chosen r' clicked (at red 2), I used the strategy below. (This is a possibly simpler version of what I described earlier, in the spec.)

For each of the N data points, _i_:
1. Find (Xri, Yri) where each value is an independent random value from Normal(0,1), i.e. the standard normal distribution
2. For the data point for display (Xi, Yi), use:
      Xi  = Xri
      Yi = Xi * rho * T + SQRT(1 - rho^2) * Yri    --T is for 'tweak'

When T = 1 the above gives a random sample, size N, from a bivariate normal population with population correlation rho.

To get the data set we want, with r (the correlation calculated for the N data points) = rho, our target correlation value, we change T until r = rho.

In other words, we keep the X values of all points the same, and shift each point vertically, using the formula above, until we get the data set correlation, r, that we want.

Bob today on zoom reminded me that Kristoffer Magnusson has a lovely demo of this here:
https://rpsychologist.com/d3/correlation/

Move the slider to change r, and see the points all adjust vertically (and the y against x line rotate) until we have the r we've chosen using the slider.

You and he mention the Cholesky decomposition. You mentioned that I'm using it in ESCI. I had no idea I was doing that! When I look up that method I quickly get into maths that is probably beyond rusty old me.

Bob says that Magnusson's code, maybe in Javascript, is available through that site. Maybe that's useful

I thought of it in much more simple terms, using Excel's 'goal seek' tool. Basically I tell it "Adjust this cell holding T until this other cell is zero." Set T initially to 1. The second cell is (rho - r). I guess Excel uses some sort of iterative hill-climbing, successive approximations method. I was going to say 'Newton's method' but I'm not sure that's correct.

In ESCI intro chapters 10-16, 'See r' page, with red 2 selected (to give 'Generate data set with chosen r'), click for new data set, and see the value of 'r of data set' (in the green area) bounce around as it converges on the chosen target r just above.

**Comment by gfmoore** [comment]
So this proved a good challenge. :) 

My second stab involves cycling through all values of T from -10 to +10 in steps of 0.01 against the entire scatter array and I look for a T which gives a minimum difference between rtarget and r calculated (rs and r in my code). (I know I should have chosen rt!!!)

This is of course highly inefficient yet seems to work for many cases and given that the JavaScript engine is so fast it doesn't seem to have any impact on responsiveness. Amazing.

I am sure that there are possibilities for improving efficiency, but let's see what you think first. Happy to be told I've got it wrong as this is new to me. I understand your reference to Newton, but my brain wasn't thinking very fast as to how to implement this kind of approach. I had a go, but I couldn't get it to work (Too many negatives and possible directions to go in.) I'll try and think it through. :) 

Bedtime (and yes I did watch the Tour as well!)

**Comment by gdcumming** [comment]
0.0.9

That approach might be brute force, but if it does the job that's wonderful.

Yesterday (0.0.8) I did random playing around and was feeling it was working well, then saw one case in which r was 0.01 different from target.

Today (0.0.9) I figured that the most challenging cases would be small N and small absolute value of r, i.e. cases likely to need a large adjustment in y values to achieve target r. That does seem to be the case. It can work fine for a dozen or more clicks, but when N and abs r are both small, we get some cases in which r is just a little off, but others in which it's way off.

I think that the reported r value always matches the displayed data dots, and the reported values of M, SD, slopes, lines, etc. But I'm not 100% confident of that because I, like most folks, can't estimate r accurately from a scatterplot, esp. for small N and r.

So I think the algorithm needs refinement somehow. I'm sure you have more ideas than I have for options. Given that when it fails it sometimes does so spectacularly suggests that it's a matter of sometimes hill climbing on the wrong hill, rather than of not quite getting to the top of the correct hill. 

One possibility may be to take a random sample, calculate its r, then take further samples until we get r within some tolerance of the target r. Then apply your method. If sampling is fast that may suffice. That strategy might guarantee we're climbing the correct hill?

If a method works reliably for N = 4 and r = 0 I would think we'd be well satisfied.

--
For us, the Tour broadcast starts at about 9.30pm usually, and the stage ends sometime around 2-3am. So we usually watch the 1 hour summary the following day. Then watch the first part of the next stage--the time of switching off depending heavily on the interest and our exhaustion levels. 

Did you love the finish into Sisteron, maybe Stage 3? Caleb Ewan, one of only two Aussies in this year's Tour, did a cunning sprint, was about 30th wheel at 300m then hopped from slipstream to slipstream, powered through a non-existent corridor next to the barriers, ducked around and won with an amazing final kick. It was wonderful watching a slomo replay with commentary from Robbie McEwan, Aussie sprinter who won 12 stages over several Tours some years back.

Caleb won 3 stages last year, including on the Champs Eleysees, so we can expect great things this year, if he can survive through the numerous mountain stages.

**Comment by gfmoore** [comment]
Yes a fantastic sprint by Ewan, amazing.

I think the issue when r = 0 occurs in the transformation

ysa[i] = (rs * xscatters[i] * T) + (Math.sqrt(1 - rs*rs) * yscatters[i]);

xscatters is the original random from normal x from and yscatters is the original random from normal y
ysa is the new suggested y values array
rs is the target i.e. 0 

So at 0 we get

ysa[i]  = (0 * xscatters[i] * T) + (Math.sqrt(1 - 0*0) * yscatters[i]);
ysa[i] = yscatters[i])   !!!!

(T goes from -10 to +10)

If I've got this right, there's no hill! The diff between rs and r is always the same. the y scatters do not get adjusted.

Does this make sense?


Any ideas?

**Comment by gdcumming** [comment]
0.0.10

As you rightly point out, rs = 0 is bound to fail! With small rs, the method looks highly inefficient, maybe not likely to converge. Going back to ESCI, with rho = 0 and N = 4, the iteration flashes past in about 1 sec, with perhaps half a dozen or a dozen values flashing up before arriving at the correct r. So Excel's Goal Seek must have some smarts, somehow.

I'm wondering whether a different brute force approach might be worth trying, given your comment about the speed of calculation you have. If that speed applies also to the taking of a sample data set, how about trying simply sampling from a population with the desired N and rs, then calculating r, and keeping going until we get a sample that happens to have r = rs, within .01 (or maybe .005). I'm guessing it might need on average a couple of hundred tries, max a few hundred. (I may be wildly wrong there.) If that takes no more than a second or two, we may have a solution? Dumb but sufficing?

With large N, perhaps taking a sample takes longer, but the sampling variability of r is smaller, so maybe in this case also the total time taken might be acceptable.

**Comment by gfmoore** [comment]
What an interesting challenge. After doing some research I discovered that what I initially tried to do, by a divide and conquer method, was also doomed to fail. The problem is to find the minimum value of an unknow convex (or concave) hill. It is a problem that is of some interest in machine or deep learning. The accepted method is to use the the technique of "gradient descent". However, you can have a problem in that you have to choose a step and it is easy to choose the wrong step and miss the target or take too long. I decided I didn't need to bother with this since on average I could halve the time to get the correct T by jumping out of the loop once the minimum point had been passed. Of course I'm assuming a smooth curve here, with just the one local minimum.

For the r = 0 problem, well I was a bit sceptical that to simply keep on generating data sets would work, but amazingly it does and often within quite a short number of iterations - perhaps up to a few thousand goes in extreme, but maybe a few decades in general.

I've used this method from abs(r <  0.1). There can be a definite wait. (I use a tolerance of  abs(rt - r) < 0.001), but it is acceptable I think. (I changed rs to rt in the code!)

Anyway see what you think.

I also added another 5 rows for the test data grid, but you can have as many rows as you want if you import a csv file.

**Comment by gdcumming** [comment]
0.0.11

I've again tried a number of data sets, and found, once again, that r, 2 of the slopes, m, sd, all seem fine, within the limits of the 2dp values. The only thing I haven't been able to check is that the red reported value of the current data set is accurate, when 'Test' is off and we're generating successive data sets all reported as having the target r, as we want. By eyeball I haven't seen any data sets that look clearly wrong, but I don't trust my eyeballing of r in scatterplots much!

Maybe you have set the tolerance to .005? It always seem to get the correct value (within our 2 dp) virtually at once. Which is fabulous! As it turns out, we may both have been trying too-complex lines of attack. Simple brute force can, in this case anyway, do the job, it seems. Great!

If you are fully confident that the reported red value of r (in Panel 2) is accurate, for the displayed dots, then let's call this done.

All we need now is 'Test [ ]' removed, and the 'dev' and version number settled. Then we could release 'correlation' along with distributions and d picture??

**Comment by gfmoore** [comment]
So you'll have to tell me if the word beta should be displayed in the menus/titles and if version should be 0.9.0 or 1.0.0

Personally I feel these are now at release status. Of course there will be slight adjustments and improvements, but that's okay. 

I double checked the displayed calculated r and where it is displayed it does recalculate r from the displayed data set. 

regards,

Gordon Moore
gm@gordonmoore.co.uk

On 05/09/2020 08:52:23, Geoff Cumming <notifications@github.com> wrote:
0.0.11
I've again tried a number of data sets, and found, once again, that r, 2 of the slopes, m, sd, all seem fine, within the limits of the 2dp values. The only thing I haven't been able to check is that the red reported value of the current data set is accurate, when 'Test' is off and we're generating successive data sets all reported as having the target r, as we want. By eyeball I haven't seen any data sets that look clearly wrong, but I don't trust my eyeballing of r in scatterplots much!
Maybe you have set the tolerance to .005? It always seem to get the correct value (within our 2 dp) virtually at once. Which is fabulous! As it turns out, we may both have been trying too-complex lines of attack. Simple brute force can, in this case anyway, do the job, it seems. Great!
If you are fully confident that the reported red value of r (in Panel 2) is accurate, for the displayed dots, then let's call this done.
All we need now is 'Test [ ]' removed, and the 'dev' and version number settled. Then we could release 'correlation' along with distributions and d picture??
